package br.com.controlepedido.gui;

import br.com.controlepedido.service.RelatorioService;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 * @author MDT
 */
public class RelatorioCreditoDebito extends javax.swing.JInternalFrame {

    RelatorioService rSer = new RelatorioService();
    SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form NewJInternalFrame
     */
    public RelatorioCreditoDebito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dccDataInicial = new com.toedter.calendar.JDateChooser();
        dccDataFinal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbNumeroPedido = new javax.swing.JRadioButton();
        txtBuscaRelatorio = new javax.swing.JTextField();
        btGerarRelatorio = new javax.swing.JButton();
        rbNomeCliente = new javax.swing.JRadioButton();
        rbDataPedido = new javax.swing.JRadioButton();
        rbPeriodoPedido = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Gerador de Relatórios - CRÉDITO E DÉBITO");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/controlepedido/imagens24x24/creditodebito.png"))); // NOI18N

        jLabel1.setText("Data Inicial:");

        jLabel2.setText("Data Final:");

        rbNumeroPedido.setText("Numero do Pedido");
        rbNumeroPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNumeroPedidoMouseClicked(evt);
            }
        });
        rbNumeroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNumeroPedidoActionPerformed(evt);
            }
        });

        txtBuscaRelatorio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBuscaRelatorio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBuscaRelatorio.setEnabled(false);

        btGerarRelatorio.setText("Gerar Relatório");
        btGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarRelatorioActionPerformed(evt);
            }
        });

        rbNomeCliente.setText(" Nome do Cliente");
        rbNomeCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNomeClienteMouseClicked(evt);
            }
        });
        rbNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomeClienteActionPerformed(evt);
            }
        });

        rbDataPedido.setText("Data do Pedido");
        rbDataPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbDataPedidoMouseClicked(evt);
            }
        });
        rbDataPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDataPedidoActionPerformed(evt);
            }
        });

        rbPeriodoPedido.setSelected(true);
        rbPeriodoPedido.setText("Período do Pedido");
        rbPeriodoPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbPeriodoPedidoMouseClicked(evt);
            }
        });
        rbPeriodoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPeriodoPedidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Digite o número ou o nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbNumeroPedido)
                                .addGap(18, 18, 18)
                                .addComponent(rbNomeCliente)
                                .addGap(18, 18, 18)
                                .addComponent(rbDataPedido)
                                .addGap(18, 18, 18)
                                .addComponent(rbPeriodoPedido))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBuscaRelatorio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dccDataInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(dccDataFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNumeroPedido)
                    .addComponent(rbNomeCliente)
                    .addComponent(rbDataPedido)
                    .addComponent(rbPeriodoPedido))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(txtBuscaRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dccDataInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dccDataFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btGerarRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPeriodoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPeriodoPedidoActionPerformed
        if (rbPeriodoPedido.isSelected()) {
            txtBuscaRelatorio.setText("");
            rbNumeroPedido.setSelected(false);
            rbNomeCliente.setSelected(false);
            rbDataPedido.setSelected(false);
            txtBuscaRelatorio.setEnabled(false);
            dccDataInicial.setEnabled(true);
            dccDataFinal.setEnabled(true);
        }
    }//GEN-LAST:event_rbPeriodoPedidoActionPerformed

    private void rbPeriodoPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbPeriodoPedidoMouseClicked
        rbPeriodoPedido.setSelected(true);
    }//GEN-LAST:event_rbPeriodoPedidoMouseClicked

    private void rbDataPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDataPedidoActionPerformed
        if (rbDataPedido.isSelected()) {
            JOptionPane.showMessageDialog(this, "Esta Função não está habilitada, entre em contato com o Programador!");
            rbDataPedido.setFocusable(false);
            rbDataPedido.setSelected(false);
        }
    }//GEN-LAST:event_rbDataPedidoActionPerformed

    private void rbDataPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbDataPedidoMouseClicked
        rbDataPedido.setSelected(true);
    }//GEN-LAST:event_rbDataPedidoMouseClicked

    private void rbNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomeClienteActionPerformed
        if (rbNomeCliente.isSelected()) {
            JOptionPane.showMessageDialog(this, "Esta Função não está habilitada, entre em contato com o Programador!");
            rbNomeCliente.setSelected(true);
            rbNomeCliente.setFocusable(false);
            rbNomeCliente.setSelected(false);
        }
    }//GEN-LAST:event_rbNomeClienteActionPerformed

    private void rbNomeClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNomeClienteMouseClicked
        rbNomeCliente.setSelected(true);
    }//GEN-LAST:event_rbNomeClienteMouseClicked

    private void rbNumeroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNumeroPedidoActionPerformed
        if (rbNumeroPedido.isSelected()) {
            txtBuscaRelatorio.setText("");
            rbNomeCliente.setSelected(false);
            rbDataPedido.setSelected(false);
            rbPeriodoPedido.setSelected(false);
            dccDataInicial.setEnabled(false);
            dccDataFinal.setEnabled(false);
            txtBuscaRelatorio.setEnabled(true);
        }
    }//GEN-LAST:event_rbNumeroPedidoActionPerformed

    private void rbNumeroPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNumeroPedidoMouseClicked
        rbNumeroPedido.setSelected(true);
    }//GEN-LAST:event_rbNumeroPedidoMouseClicked

    private void btGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarRelatorioActionPerformed
        if (rbPeriodoPedido.isSelected()) {
            if(dccDataInicial.getDate() == null || dccDataFinal.getDate() == null){
                JOptionPane.showMessageDialog(this, "É necessário selecionar as datas inicial e final!!!");
            }else{
                Date datai, dataf;
                datai = dccDataInicial.getDate();
                dataf = dccDataFinal.getDate();
                rSer.CriarRelatorioDatasCreditoDebito(datai, dataf);
            }
        } else if (rbNumeroPedido.isSelected() && txtBuscaRelatorio.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "É necessário digitar o numero do pedido!!!");
        } else if (rbNumeroPedido.isSelected()) {
            try {
                Long numero = Long.parseLong(txtBuscaRelatorio.getText());
                rSer.CriarRelatorioCreditoDebito(numero);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "É necessário Digitar Números Inteiros!!!" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btGerarRelatorioActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerarRelatorio;
    private com.toedter.calendar.JDateChooser dccDataFinal;
    private com.toedter.calendar.JDateChooser dccDataInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbDataPedido;
    private javax.swing.JRadioButton rbNomeCliente;
    private javax.swing.JRadioButton rbNumeroPedido;
    private javax.swing.JRadioButton rbPeriodoPedido;
    private javax.swing.JTextField txtBuscaRelatorio;
    // End of variables declaration//GEN-END:variables
}
